config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :static_pages, only: [], path: '/' do
    collection do
      get :home
      post :send_email
    end
  end

  resources :blogs, only: :show

  namespace :admin do
    resources :blogs do
      member do
        put :activate
        put :deactivate
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :cover_image, CoverImageUploader

  scope :cover_blog, -> { where(is_cover: true).first }
  scope :recent_blogs, -> { where(is_cover: false).select(:id, :title, :slug).last(8) }
  scope :other_recent_blogs, -> (curr_id = nil) { where.not(id: curr_id).select(:id, :title, :slug).last(8) }
  scope :all_active, -> { where(is_active: true) }
  scope :all_inactive, -> { where(is_active: false) }

  validates_presence_of :title, :content

  def date_posted
    ["Posted", created_at.strftime("%d %B %Y")].join(" ")
  end

  def previous_blog
    self.class.all_active.where("created_at < ?", created_at).order(created_at: :asc).last
  end

  def next_blog
    self.class.all_active.where("created_at > ?", created_at).order(created_at: :asc).first
  end

  def deactivate
    update_attribute(:is_active, false)
  end

  def activate
    update_attribute(:is_active, true)
  end

  def self.reset_other_cover_blog(new_cover_blog_id)
    other_cover_blog = Blog.where(is_cover: true).where.not(id: new_cover_blog_id).first
    return if other_cover_blog.nil?
    other_cover_blog.update_attribute(:is_cover, false)
  end

  private

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :activate, :deactivate]

  def index
    @blogs = Blog.all.order('updated_at DESC').page(params[:page])
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        Blog.reset_other_cover_blog(@blog.id) if @blog.is_cover
        format.html { redirect_to admin_blog_url(@blog), notice: "Blog was successfully created" }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        Blog.reset_other_cover_blog(@blog.id) if @blog.is_cover
        format.html { redirect_to admin_blog_url(@blog), notice: "#{@blog.title} was successfully updated" }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog_title = @blog.title
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url, notice: "#{@blog_title} was successfully deleted" }
      format.json { head :no_content }
    end
  end

  def deactivate
    @blog.deactivate
    respond_to do |format|
      format.html { redirect_to admin_blogs_url, notice: "#{@blog.title} is now hidden from public viewing" }
      format.json { head :no_content }
    end
  end

  def activate
    @blog.activate
    respond_to do |format|
      format.html { redirect_to admin_blogs_url, notice: "#{@blog.title} is now available for public viewing" }
      format.json { head :no_content }
    end
  end

  private

  def blog_params
    params.require(:blog).permit(
      :title,
      :content,
      :is_cover,
      :cover_image
    )
  end

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show]

  def show
    @other_recent_blogs = Blog.all_active.other_recent_blogs(@blog.id)
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :send_email_params, only: [:send_email]

  def home
    @cover_blog = Blog.cover_blog
    @cover_blog = Blog.order('updated_at desc').first if @cover_blog.nil?
    @recent_blogs = Blog.all_active.recent_blogs
  end

  def send_email
    ContactMailer.contact_email(send_email_params).deliver
    redirect_to root_url(email_success: true)
  end

  private
  def send_email_params
    params.require(:send_email).permit(:name, :email, :company, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/blogs/_form.html.haml
= simple_form_for [:admin, @blog] do |f|
  .panel.panel-default
    .panel-body
      .col-md-12
        .form-group
          = f.input :is_cover, label: "Set as cover blog"
        .form-group
          = f.input :title, placeholder: "Blog Title"
        .form-group
          = f.input :content,  placeholder: "Blog Content", input_html: { rows: 10, class: "tinymce" }
        .form-group
          = f.input :cover_image, as: :file
          - if f.object.cover_image.present?
            = image_tag(f.object.cover_image.large_thumb.url)

      .col-md-12
        .form-group
          - if @blog.new_record?
            = f.button :submit, "Create Blog", class: "btn btn-primary"
            = link_to "Cancel", admin_blogs_path, class: "btn btn-default"
          - else
            = f.button :submit, "Update Blog", class: "btn btn-primary"
            = link_to "Cancel", admin_blog_path(@blog), class: "btn btn-default"
= tinymce

app/views/admin/blogs/edit.html.haml
#blogs_admin
  .col-xs-12
    = render partial: 'layouts/header', locals: {addl_navbar_class: "other-header"}
    .col-xs-12
      .blog-title
        = "Update Blog"

      = render 'form'

app/views/admin/blogs/index.html.haml
#blogs_admin
  .col-xs-12
    = render partial: 'layouts/header', locals: {addl_navbar_class: "other-header"}
    = render 'layouts/messages'
    .col-xs-12.col-md-12
      .blog-title
        = "Blogs index"
      %br/
      = link_to "Create Blog", new_admin_blog_path, class: "btn btn-primary btn-md"
      %hr
      .table-responsive
        %table.table.table-bordered.table-hover.table-striped
          %thead
            %tr
              %th= "Title"
              %th= "Created At"
              %th= "Last Updated At"
              %th= "Actions"
          %tbody
            - @blogs.each do |blog|
              %tr
                %td{ title: blog.title }
                  - if blog.is_cover
                    %i.glyphicon.glyphicon-star{ style: "cursor: pointer;", title: "Cover blog" }
                  = blog.title.truncate(100)
                %td= blog.created_at.strftime("%B %d, %Y %H:%M:%S")
                %td= blog.updated_at.strftime("%B %d, %Y %H:%M:%S")
                %td
                  = link_to "Show", admin_blog_path(blog), class: "btn btn-primary btn-xs"
                  = link_to "Edit", edit_admin_blog_path(blog), class: "btn btn-primary btn-xs"
                  - if blog.is_active
                    = link_to "Hide", deactivate_admin_blog_path(blog), method: :put, class: "btn btn-primary btn-xs", data: { confirm: "This will hide this blog from public viewing. Are you sure?" }
                  - else
                    = link_to "Show", activate_admin_blog_path(blog), method: :put, class: "btn btn-primary btn-xs", data: { confirm: "This will show this blog from public viewing. Are you sure?" }
                  = link_to "Delete", admin_blog_path(blog), method: :delete, class: "btn btn-primary btn-xs", data: { confirm: "This will completely remove this blog. Are you sure?" }
      = paginate @blogs
      = page_entries_info @blogs

app/views/admin/blogs/new.html.haml
#blogs_admin
  .col-xs-12
    = render partial: 'layouts/header', locals: {addl_navbar_class: "other-header"}
    .col-xs-12
      .blog-title
        = "Create Blog"

      = render 'form'

app/views/admin/blogs/show.html.haml
#blogs_admin
  .col-xs-12
    = render partial: 'layouts/header', locals: {addl_navbar_class: "other-header"}
    = render 'layouts/messages'
    .col-xs-12.col-md-12
      .blog-title
        - if @blog.is_cover
          %i.glyphicon.glyphicon-star{ style: "cursor: pointer;", title: "Cover blog" }
        = @blog.title rescue ""
      %br/
      = link_to "Edit this blog", edit_admin_blog_path(@blog), class: "btn btn-primary"
      = link_to "Blogs Index Page", admin_blogs_path, class: "btn btn-primary"
      %hr
      - if @blog.cover_image.present?
        .center.blog-cover-image
          = image_tag(@blog.cover_image.url)
      .blog-body
        = raw @blog.content.html_safe rescue ""
      %p.blog-date-posted
        = @blog.date_posted rescue ""
      %hr

      .center.blog-navigation
        - previous_blog = @blog.previous_blog
        - next_blog = @blog.next_blog
        - if previous_blog
          = link_to "<< Previous", admin_blog_path(@blog.previous_blog)
        - else
          = link_to "<< Previous", "", disabled: true, class: "disabled"
        = " | "
        - if next_blog
          = link_to "Next >>", admin_blog_path(@blog.next_blog)
        - else
          = link_to "Next >>", "", disabled: true, class: "disabled"

:javascript
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
    });
  });

app/views/blogs/_other_recent_posts.html.haml
%hr{ style: "border: none;" }
.recent-posts-title
  = "Recent posts"
%hr
.recent-posts-list
  %ul
    - @other_recent_blogs.each do |recent_blog|
      %li= link_to recent_blog.title, recent_blog

app/views/blogs/show.html.haml
#blogs_show
  .col-xs-12
    = render partial: 'layouts/header', locals: {addl_navbar_class: "other-header"}
    .col-xs-12.col-md-8
      .blog-title
        = @blog.title rescue ""
      %hr
      - if @blog.cover_image.present?
        .center.blog-cover-image
          = image_tag(@blog.cover_image.url)
      .blog-body
        = raw @blog.content.html_safe rescue ""
      .blog-social-links
        .fb-share-button{ "data-href" => blog_url(@blog), "data-layout" => "button", "data-mobile-iframe" => "true", "data-size" => "large" }
          = link_to "Share", "https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&src=sdkpreparse", target: "_blank", class: "fb-xfbml-parse-ignore"
        = link_to "Tweet", "https://twitter.com/intent/tweet?text=Check%20this%20out!&url=#{blog_url(@blog)}", class: "twitter-share-button", "data-size": "large"
      .row
      %p.blog-date-posted
        = @blog.date_posted rescue ""
      %hr

      .center.blog-navigation
        = link_to "<< Previous", @blog.previous_blog, disabled: @blog.previous_blog.nil?, class: "#{@blog.previous_blog.nil? ? 'disabled' : ''}"
        = " | "
        = link_to "Next >>", @blog.next_blog, disabled: @blog.next_blog.nil?, class: "#{@blog.next_blog.nil? ? 'disabled' : ''}"

    .col-xs-12.col-md-4#follow
      = render partial: "static_pages/like_and_follow"
      = render partial: "blogs/other_recent_posts"

:javascript
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
    });
  });

app/views/layouts/_footer.html.haml
%footer.footer
  .container-fluid.footer-container.white_gray_gradient
    %h5
      .row
        .col-sm-12
          .col-sm-12
            .copyright
              %p= "© 2017 imagineAR"
              %p= "Legal"
              %p= "Privacy Policy"

app/views/layouts/_header.html.haml
- if local_assigns[:addl_navbar_class].present?
  %nav.navbar.navbar-default.navbar-fixed-top{ :role => "navigation", class: addl_navbar_class }
    .container-fluid.header-container
      .navbar-header
        %button.navbar-toggle.collapsed{ "data-target" => "#imagine-ar-navbar", "data-toggle" => "collapse", :type => "button" }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand#logo{ :href => root_path }
          %span= image_tag("imagineAR_logo.png")
      #imagine-ar-navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right#navlinks
          %li
            = link_to "SERVICES", "#{root_url}#ar-carousel"
          %li
            = link_to "NEWS", "#{root_url}#social"
          %li
            = link_to "ABOUT", "#{root_url}#we-are-imagineers"
          %li
            = link_to "CONTACT", "#{root_url}#contact-us-top"
- else
  %nav.navbar.navbar-fixed-top{ :role => "navigation" }
    .container-fluid.header-container
      .navbar-header
        %button.navbar-toggle.collapsed{ "data-target" => "#imagine-ar-navbar", "data-toggle" => "collapse", :type => "button" }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand#logo{ :href => root_path }
          %span= image_tag("imagineAR_logo.png")
      #imagine-ar-navbar.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right#navlinks
          %li
            = link_to "SERVICES", "#ar-carousel"
          %li
            = link_to "NEWS", "#social"
          %li
            = link_to "ABOUT", "#we-are-imagineers"
          %li
            = link_to "CONTACT", "#contact-us-top"

:javascript
  var $root = $('html, body');
  $('#navlinks a').click(function() {
      $root.animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
      }, 500);

      $('#navlinks a').each(function(i,obj) {
        $(obj).removeClass('active');
      });
      $(this).addClass('active');
      return false;
  });

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id: "flash_message_div"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title imagineAR
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    / = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    / = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    / = render 'layouts/header'

    .container-fluid.main-content-container
      = yield

  = render 'layouts/footer'

:javascript
  $(document).ready(function(){
    window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  });

app/views/static_pages/_about_us.html.haml
= image_tag("turtle.png", class: "turtle")
.col-xs-12#we-are-imagineers.no-padding-left.no-padding-right
  .center.jumbotron
    .about-us-title
      %p{style: "display: inline;"}
        = "We are "
        .imagineers{style: "display: inline;"}
          = "imagineers"
      %p= "focusing on both art and tech."
    .about-us-body
      %p
        = "We believe that cutting-edge technology is AR's driving muscle behind robust, feature-rich and highly interactive applications. While art and creativity is the one that connects, inspires and touches people. With both, we are able to deliver the most compelling AR experiences."
      %br/
      %br/
      %p
        = "Our team is comprised of industry experts with years of experience developing mobile applications, games, AR and VR. We promise to deliver high quality software and top-notch visual graphics for your app project."
.col-xs-12.no-padding-left.no-padding-right
  .center.contact-us.white_gray_gradient
    = link_to "Contact Us", "#contact-us-top", class: "btn btn-lg btn-primary"

:javascript
  $('.contact-us a').click(function() {
      $root.animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
      }, 500);
      return false;
  });

app/views/static_pages/_blog.html.haml
.col-xs-12
  .col-xs-12.col-md-8#blog
    = render partial: "cover_blog"
  .col-xs-12.col-md-4#follow
    = render partial: "like_and_follow"
    = render partial: "recent_posts"

app/views/static_pages/_carousel.html.haml
.col-xs-12
  .row
    .col-md-6.col-xs-6
      .center
        = image_tag("carousel1.png", class: "carousel-img")
    .col-md-6.col-xs-6
      .center
        = image_tag("carousel2.png", class: "carousel-img")

  .row.white_gray_gradient
    .col-md-6.col-xs-6
      .row
        .col-md-4.col-md-offset-4
          %hr
      .center
        %strong.carousel-caption-title
          = "AR App Development"
      .row
        .col-md-4.col-md-offset-4
          %p.carousel-caption-desc.center
            = "We help you build the perfect mobile AR app for your business. From enterprise apps to AR games."
      .center.inquire-btn
        = link_to "Inquire Now", "#contact-us-top", class: "btn btn-lg btn-primary"
    .col-md-6.col-xs-6
      .row
        .col-md-4.col-md-offset-4
          %hr
      .center
        %strong.carousel-caption-title
          = "AR Hosting"
      .row
        .col-md-4.col-md-offset-4
          %p.carousel-caption-desc.center
            = "We craft compelling AR experiences for your product and make it accessible to all."
      .center.inquire-btn
        = link_to "Inquire Now", "#contact-us-top", class: "btn btn-lg btn-primary"

:javascript
  $('.inquire-btn a').click(function() {
      $root.animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
      }, 500);
      return false;
  });

app/views/static_pages/_contact_us.html.haml
.col-xs-12#contact-us-top
  .col-xs-4.col-sm-8.col-md-6.contact-us-form
    .form-group.row
      .col-md-9.col-md-offset-2{ style: "display: inline;" }
        = image_tag("imagineAR_logo.png")
  .pull-right{ style: "display: inline;" }
    = link_to image_tag("top.png", class: "to-top"), ""
.col-xs-12#contact-us
  .center.contact-us-title
    %p{ style: "display: inline;" }
      = "GET IN TOUCH"

  .row
  .col-sm-12.col-md-6.contact-us-form
    = render 'contact_us_form'

  .col-sm-12.col-md-6.contact-us-details
    %p
      = "We are accepting projects!"
    %br/
    %p
      = "Tell us about your app idea, hosting"
    %p
      = " inquiry, or ask for a project quote."
    %br/
    %br/
    %br/

    .address-details
      .row
      .col-xs-1.col-sm-1.no-padding-left.no-padding-right
        = image_tag("location_bullet.png")
      .col-xs-11.col-sm-11.no-padding-left{ style: "margin-bottom: 20px;" }
        %p= "Lot 5 Block 17 Arquiza Street,"
        %p= "Phase 2B Ciudad Real Subdivision"
        %p= "San Jose del Monte City, Bulacan"
        %p= "Philippines"

    .phone-details
      .row
      .col-xs-1.col-sm-1.no-padding-left.no-padding-right
        = image_tag("phone_bullet.png")
      .col-xs-11.col-sm-11.no-padding-left{ style: "margin-bottom: 20px;" }
        %p= "(02) 351-7393"

    .email-details
      .row
      .col-xs-1.col-sm-1.no-padding-left.no-padding-right
        = image_tag("email_bullet.png")
      .col-xs-11.col-sm-11.no-padding-left{ style: "margin-bottom: 20px;" }
        %p.email
          = mail_to "info@imagine-ar.com"

:javascript
  $('.to-top').click(function() {
      $root.animate({
        scrollTop: 0
      }, 500);
      return false;
  });

app/views/static_pages/_contact_us_form.html.haml
= form_for :send_email, url: send_email_static_pages_path, html: { id: "send_email_form" } do |f|
  .form-group.row
    .col-md-9.col-md-offset-2
      = f.text_field :name, class: "form-control", type: "text", placeholder: "Your Name*"
  .form-group.row
    .col-md-9.col-md-offset-2
      = f.text_field :email, class: "form-control", type: "email", placeholder: "Your Email*"
  .form-group.row
    .col-md-9.col-md-offset-2
      = f.text_field :company, class: "form-control", type: "text", placeholder: "Your Company"
  .form-group.row
    .col-md-9.col-md-offset-2
      = f.text_area :message, class: "form-control", type: "textarea", placeholder: "Your Message*", rows: 5
  .form-group.row
    .col-md-3.col-xs-6.col-md-offset-2
      = f.submit "Send", class: "btn btn-default btn-lg btn-block contact-us-send", type: "submit"

:javascript
  $("#send_email_form").validate({
    rules: {
      'send_email[name]': { required: true },
      'send_email[email]': { required: true },
      'send_email[message]': { required: true, minlength: 10 },
    }
  });

app/views/static_pages/_cover_blog.html.haml
.blog-title
  = @cover_blog.title rescue ""
%hr
- if @cover_blog.cover_image.present?
  .center.blog-cover-image
    = image_tag(@cover_blog.cover_image.url)
.blog-body
  %p
    = truncate(strip_tags(@cover_blog.content.html_safe), escape: false, length: 340) rescue ""
.readmore-link
  = link_to "Read More >>", blog_path(@cover_blog)
.blog-social-links
  .fb-share-button{ "data-href" => blog_url(@cover_blog), "data-layout" => "button", "data-mobile-iframe" => "true", "data-size" => "large" }
    = link_to "Share", "https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&src=sdkpreparse", target: "_blank", class: "fb-xfbml-parse-ignore"
  = link_to "Tweet", "https://twitter.com/intent/tweet?text=Check%20this%20out!&url=#{blog_url(@cover_blog)}", class: "twitter-share-button", "data-size": "large"
.row
%p.blog-date-posted
  = @cover_blog.date_posted rescue ""

app/views/static_pages/_email_success_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", id: "send_email_success_modal"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
          %strong= "Email successfully sent"
      .modal-body
        %p= "Thank you for taking the time to contact us!"

:javascript
  $('#send_email_success_modal').modal('show');
  window.history.pushState("object or string", "Title", '#{root_url}');

app/views/static_pages/_learnmore.html.haml
.col-xs-12
  = render 'layouts/header'
  .col-xs-10.col-md-8.col-lg-6.col-md-offset-1
    .center.jumbotron
      .learnmore-title
        %h1= "Your ideas brought to life through AR."
        = link_to "Learn More", "#ar-carousel", class: "btn btn-lg btn-primary learnmore-link"

:javascript
  var $root = $('html, body');
  $('.learnmore-link').click(function() {
      $root.animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
      }, 500);
      return false;
  });

app/views/static_pages/_like_and_follow.html.haml
.follow-title
  = "like and follow imagineAR"
%hr
.follow-body
  %p
    = "<strong><i>imagineAR</i></strong> seeks to inspire and innovate through cutting-edge technology, creative digital graphics and playful arts.".html_safe
  %p
    = "We envision a world where dreams and ideas co-exist with reality."
  %p
    = "We'll keep you updated with the latest trends in tech, art, and games for the AR/VR/MR platforms."
.follow-social-links
  .fb-like{ "data-action" => "like", "data-href" => "https://www.facebook.com/imaginear.ph/", "data-layout" => "standard", "data-share" => "true", "data-show-faces" => "false", "data-size" => "large" }
  = link_to "Follow", "https://twitter.com/imagineAR_", "data-size" => "large", "data-show-screen-name" => "false", class: "twitter-follow-button"

app/views/static_pages/_partners.html.haml
.col-xs-12#partners
  .col-xs-12
    .partners-title
      = "Partners"
  .col-sm-12.col-md-2.partner-logo
    = link_to image_tag("partner1.png"), "http://thecoffeecreatives.com", target: "_blank"
  .col-sm-12.col-md-2.partner-logo
    = link_to image_tag("partner2.png"), "http://consonantsolutions.com/", target: "_blank"
  .col-sm-12.col-md-2.partner-logo
    = link_to image_tag("partner3.png"), "https://www.facebook.com/vrphilippines/", target: "_blank"

app/views/static_pages/_recent_posts.html.haml
%hr{ style: "border: none;" }
.recent-posts-title
  = "Recent posts"
%hr
.recent-posts-list
  %ul
    - @recent_blogs.each do |recent_blog|
      %li= link_to recent_blog.title, "#"

app/views/static_pages/home.html.haml
#learnmore
  = render 'learnmore'

#ar-carousel
  = render 'carousel'

#social
  = render 'blog'

.col-xs-12.social-abtus-separator.white_gray_gradient
  .col-xs-12
    %hr

#about-us
  = render 'about_us'

= render 'contact_us'

= render 'partners'

- if params[:email_success].present?
  = render "email_success_modal"